# define a base json template
# for a new subject, start w/ localizer as active tab
# fill in full protocol
from library import save_json
import time
from copy import deepcopy

def get_json(subject_id):
    json = {"subject_id":subject_id,
        "placebo":False,
        "time":time.ctime(),
        "script":None,
        "Protocol":[{"name":"Localizer",
                     "active":True, 
                     "complete":False,
                     "ui":"loop",
		             "Steps":[{"text":"Test Setup",
	                          "ui":"button","class":"btn",
	                          "disabled":False,
	                          "time":"",
	                          "history":[],
	                          "action":"lib.testFull()",
                              "clicked":False,
                              "enabled_when":None,
	                          "value":"0.0",
                              "on_click":"disabled = False"},

	                        {"text":"Acquire localizer32", 
	                        "ui":"checkbox",
	                        "disabled":True,
	                        "checked":False,
                            "clicked":False,
	                        "time":"",
	                        "history":[],
	                        "value":"0.1",
                            "enabled_when":"0.0 and not 0.1",
                            "on_click":"disabled = True"},

	                        {"text":"Acquire AAScout", 
	                        "ui":"checkbox",
	                        "disabled":True,
	                        "checked":False,
                            "clicked":False,
	                        "time":"",
	                        "history":[], 
                            "value":"0.2",
                            "on_click":"disabled = True",
                            "enabled_when":"0.0 and 0.1 and not 0.2"},

	                        {"text":"Acquire MEMPRAGE",
	                        "ui":"checkbox",
                            "disabled":True,
                            "checked":False,"clicked":False,
                            "time":"",
                            "history":[],
                            "value":"0.3","on_click":"disabled = True",
                            "enabled_when":"0.2 and not 0.3"}
                            ]
                            },
                    {"name":"Visit 1","ui":"loop",
                     "Steps":[{"text":"Run Tests",
                                "ui":"button","class":"btn",
                                "disabled":False,
                                "time":"",
                                "history":[],"clicked":False,
                                "value":"1.0","on_click":"disabled = False",
                                "action":"lib.testFull()","enabled_when":None},
                              {"text":"Acquire localizer32 ",
                                "ui":"checkbox",
                                "disabled":True,
                                "checked":False,"clicked":False,
                                "time":"",
                                "history":[],"on_click":"disabled = False",
                                "value":"1.1","enabled_when":"1.0 and not 1.1"},
                              {"text":"Acquire AAScout", 
                                "ui":"checkbox",
                                "disabled":True,
                                "checked":False,"clicked":False,
                                "time":"",
                                "history":[],"on_click":"disabled = False",
                                "value":"1.2","enabled_when":"1.1 and not 1.2"},
                              {"text":"RT Run", 
                                "ui":"loop", 
                                "runNum":1,
                                "time":"",
                                "history":[], 
                                "value":"1.3","on_click":"disabled = False",
                                "Steps":[{"text":"Start Murfi",
                                         "ui":"button",
                                         "clicked":False,
                                         "action":"self.murfiproc,_ = lib.doMurfi(\"%s\",1,1,self,loc=\'1.3.0\')"%subject_id,
                                         "disabled":False,
                                         "on_click":None,
                                         "value":"1.3.0", 
                                         "enabled_when":None,
                                         "class":"btn dataUpdate"},
                                         {"text":"Start Serve",
                                          "ui":"button","clicked":False,
                                          "disabled":False,
                                          "on_click":None,
                                          "action":"self.serveproc,_=lib.doServ(\"%s\",1,1,self,loc=\'1.3.1\')"%subject_id,
                                          "value":"1.3.1",
                                          "enabled_when":None,
                                          "class":"btn"},
                                         {"text":"Redo Run",
                                          "ui":"button",
                                          "class":"btn",
                                          "clicked":False,
                                          "disabled":False,
                                          "on_click":None,
                                          "value":"1.3.2",
                                          "enabled_when":None,
                                          "action":"lib.redoRun(self,\"1.3.0\",\"1.3.1\")"}]},
                              {"text":"RT Run", 
                                "ui":"loop", 
                                "runNum":2,
                                "time":"",
                                "history":[], 
                                "value":"1.4","on_click":"disabled = False",
                                "Steps":[{"text":"Start Murfi",
                                         "ui":"button",
                                         "clicked":False,
                                         "action":"self.murfiproc,_ = lib.doMurfi(\"%s\",1,2,self,loc=\'1.4.0\')"%subject_id,
                                         "disabled":False,
                                         "on_click":None,
                                         "value":"1.4.0", 
                                         "enabled_when":None,
                                         "class":"btn dataUpdate"},
                                         {"text":"Start Serve",
                                          "ui":"button","clicked":False,
                                          "disabled":False,
                                          "on_click":None,
                                          "action":"self.serveproc,_=lib.doServ(\"%s\",1,2,self,loc=\'1.4.1\')"%subject_id,
                                          "value":"1.4.1",
                                          "enabled_when":None,
                                          "class":"btn"},
                                         {"text":"Redo Run",
                                          "ui":"button",
                                          "class":"btn",
                                          "clicked":False,
                                          "disabled":False,
                                          "on_click":None,
                                          "value":"1.4.2",
                                          "enabled_when":None,
                                          "action":"lib.redoRun(self,\"1.4.0\",\"1.4.1\")"}]},
{"text":"RT Run", 
                                "ui":"loop", 
                                "runNum":3,
                                "time":"",
                                "history":[], 
                                "value":"1.5","on_click":"disabled = False",
                                "Steps":[{"text":"Start Murfi",
                                         "ui":"button",
                                         "clicked":False,
                                         "action":"self.murfiproc,_ = lib.doMurfi(\"%s\",1,3,self,loc=\'1.5.0\')"%subject_id,
                                         "disabled":False,
                                         "on_click":None,
                                         "value":"1.5.0", 
                                         "enabled_when":None,
                                         "class":"btn dataUpdate"},
                                         {"text":"Start Serve",
                                          "ui":"button","clicked":False,
                                          "disabled":False,
                                          "on_click":None,
                                          "action":"self.serveproc,_=lib.doServ(\"%s\",1,3,self,loc=\'1.5.1\')"%subject_id,
                                          "value":"1.5.1",
                                          "enabled_when":None,
                                          "class":"btn"},
                                         {"text":"Redo Run",
                                          "ui":"button",
                                          "class":"btn",
                                          "clicked":False,
                                          "disabled":False,
                                          "on_click":None,
                                          "value":"1.5.2",
                                          "enabled_when":None,
                                          "action":"lib.redoRun(self,\"1.5.0\",\"1.5.1\")"}]},
{"text":"RT Run", 
                                "ui":"loop", 
                                "runNum":4,
                                "time":"",
                                "history":[], 
                                "value":"1.6","on_click":"disabled = False",
                                "Steps":[{"text":"Start Murfi",
                                         "ui":"button",
                                         "clicked":False,
                                         "action":"self.murfiproc,_ = lib.doMurfi(\"%s\",1,4,self,loc=\'1.6.0\')"%subject_id,
                                         "disabled":False,
                                         "on_click":None,
                                         "value":"1.6.0", 
                                         "enabled_when":None,
                                         "class":"btn dataUpdate"},
                                         {"text":"Start Serve",
                                          "ui":"button","clicked":False,
                                          "disabled":False,
                                          "on_click":None,
                                          "action":"self.serveproc,_=lib.doServ(\"%s\",1,4,self,loc=\'1.6.1\')"%subject_id,
                                          "value":"1.6.1",
                                          "enabled_when":None,
                                          "class":"btn"},
                                         {"text":"Redo Run",
                                          "ui":"button",
                                          "class":"btn",
                                          "clicked":False,
                                          "disabled":False,
                                          "on_click":None,
                                          "value":"1.6.2",
                                          "enabled_when":None,
                                          "action":"lib.redoRun(self,\"1.6.0\",\"1.6.1\")"}]},
                              {"text":"RT Run", 
                                "ui":"loop", 
                                "runNum":5,
                                "time":"",
                                "history":[], 
                                "value":"1.7","on_click":"disabled = False",
                                "Steps":[{"text":"Start Murfi",
                                         "ui":"button",
                                         "clicked":False,
                                         "action":"self.murfiproc,_ = lib.doMurfi(\"%s\",1,5,self,loc=\'1.7.0\')"%subject_id,
                                         "disabled":False,
                                         "on_click":None,
                                         "value":"1.7.0", 
                                         "enabled_when":None,
                                         "class":"btn dataUpdate"},
                                         {"text":"Start Serve",
                                          "ui":"button","clicked":False,
                                          "disabled":False,
                                          "on_click":None,
                                          "action":"self.serveproc,_=lib.doServ(\"%s\",1,5,self,loc=\'1.7.1\')"%subject_id,
                                          "value":"1.7.1",
                                          "enabled_when":None,
                                          "class":"btn"},
                                         {"text":"Redo Run",
                                          "ui":"button",
                                          "class":"btn",
                                          "clicked":False,
                                          "disabled":False,
                                          "on_click":None,
                                          "value":"1.7.2",
                                          "enabled_when":None,
                                          "action":"lib.redoRun(self,\"1.7.0\",\"1.7.1\")"}]},
{"text":"RT Run", 
                                "ui":"loop", 
                                "runNum":6,
                                "time":"",
                                "history":[], 
                                "value":"1.8","on_click":"disabled = False",
                                "Steps":[{"text":"Start Murfi",
                                         "ui":"button",
                                         "clicked":False,
                                         "action":"self.murfiproc,_ = lib.doMurfi(\"%s\",1,6,self,loc=\'1.8.0\')"%subject_id,
                                         "disabled":False,
                                         "on_click":None,
                                         "value":"1.8.0", 
                                         "enabled_when":None,
                                         "class":"btn dataUpdate"},
                                         {"text":"Start Serve",
                                          "ui":"button","clicked":False,
                                          "disabled":False,
                                          "on_click":None,
                                          "action":"self.serveproc,_=lib.doServ(\"%s\",1,6,self,loc=\'1.8.1\')"%subject_id,
                                          "value":"1.8.1",
                                          "enabled_when":None,
                                          "class":"btn"},
                                         {"text":"Redo Run",
                                          "ui":"button",
                                          "class":"btn",
                                          "clicked":False,
                                          "disabled":False,
                                          "on_click":None,
                                          "value":"1.8.2",
                                          "enabled_when":None,
                                          "action":"lib.redoRun(self,\"1.8.0\",\"1.8.1\")"}]},
                              {"text":"Complete RTVisit",
                               "ui":"button",
                               "class":"btn",
                               "clicked":False,
                               "action":"lib.completeVisit(self,\'1.5\')",
                               "disabled":False,
                               "time":"",
                               "history":[],"on_click":"disabled = False",
                               "value":"1.4","enabled_when":None}],
                     "stepIndex":{},
                     "active":False,
                     "complete":False}
                            ]} 
    
    return json

