# define a base json template
# for a new subject, start w/ localizer as active tab
# fill in full protocol
from library import save_json
import time
from copy import deepcopy
json = {"subject_id":"",
        "time":time.ctime(),
        "Protocol":[{"name":"Localizer",
                     "active":True, 
                     "complete":False,
                     "ui":"loop",
		             "Steps":[{"text":"Test Setup",
	                          "ui":"button",
	                          "disabled":False,
	                          "time":"",
	                          "history":[],
	                          "action":"lib.testFull()",
                              "clicked":False,
                              "enabled_when":None,
	                          "value":"0.0",
                              "on_click":"disabled = False"},

	                        {"text":"Acquire localizer32", 
	                        "ui":"checkbox",
	                        "disabled":True,
	                        "checked":False,
                            "clicked":False,
	                        "time":"",
	                        "history":[],
	                        "value":"0.1",
                            "enabled_when":"0.0 and not 0.1",
                            "on_click":"disabled = True"},

	                        {"text":"Acquire AAScout", 
	                        "ui":"checkbox",
	                        "disabled":True,
	                        "checked":False,
                            "clicked":False,
	                        "time":"",
	                        "history":[], 
                            "value":"0.2",
                            "on_click":"disabled = True",
                            "enabled_when":"0.0 and 0.1"},

	                        {"text":"Acquire MEMPRAGE",
	                        "ui":"checkbox",
                            "disabled":True,
                            "checked":False,"clicked":False,
                            "time":"",
                            "history":[],
                            "value":"0.3","on_click":"disabled = True",
                            "enabled_when":"0.2"}
                            ]
                            },
                    {"name":"Visit 1","ui":"loop",
                     "Steps":[{"text":"Run Tests",
                                "ui":"button",
                                "disabled":False,
                                "time":"",
                                "history":[],
                                "value":"1.0","on_click":"disabled = False",
                                "action":"lib.testFull()","enabled_when":None},
                              {"text":"Acquire localizer32 ",
                                "ui":"checkbox",
                                "disabled":True,
                                "checked":False,
                                "time":"",
                                "history":[],"on_click":"disabled = False",
                                "value":"1.1","enabled_when":None},
                              {"text":"Acquire AAScout", 
                                "ui":"checkbox",
                                "disabled":True,
                                "checked":False,
                                "time":"",
                                "history":[],"on_click":"disabled = False",
                                "value":"1.2","enabled_when":None},
                              {"text":"RT Run", 
                                "ui":"loop", 
                                "runNum":1,
                                "time":"",
                                "history":[], 
                                "value":"1.3","on_click":"disabled = False",
                                "Steps":[{"text":"Start Murfi",
                                         "ui":"button",
                                         "disabled":True,"on_click":"disabled = False",
                                         "value":"1.3.0","enabled_when":None},
                                         {"text":"Launch RT",
                                          "ui":"button",
                                          "disabled":True,"on_click":"disabled = False",
                                          "value":"1.3.1","enabled_when":None},
                                         {"text":"Start Serve",
                                          "ui":"button",
                                          "disabled":True,"on_click":"disabled = False",
                                          "value":"1.3.2","enabled_when":None},
                                         {"text":"Redo Run",
                                          "ui":"button",
                                          "disabled":True,"on_click":"disabled = False",
                                          "value":"1.3.3","enabled_when":None}] },
                              {"text":"RT Run", 
                                "ui":"loop", 
                                "runNum":2,
                                "time":"",
                                "history":[], 
                                "value":"1.4",
                                "Steps":[{"text":"Start Murfi",
                                         "ui":"button",
                                         "disabled":True,"on_click":"disabled = False",
                                         "value":"1.4.0","enabled_when":None},
                                         {"text":"Launch RT",
                                          "ui":"button",
                                          "disabled":True,"on_click":"disabled = False",
                                          "value":"1.4.1","enabled_when":None},
                                         {"text":"Start Serve",
                                          "ui":"button",
                                          "disabled":True,"on_click":"disabled = False",
                                          "value":"1.4.2","enabled_when":None},
                                         {"text":"Redo Run",
                                          "ui":"button",
                                          "disabled":True,"on_click":"disabled = False",
                                          "value":"1.4.3","enabled_when":None}] },
                              {"text":"Complete RTVisit",
                               "ui":"button",
                               "disabled":True,
                               "time":"",
                               "history":[],"on_click":"disabled = False",
                               "value":"1.5","enabled_when":None}],
                     "stepIndex":{},
                     "active":False,
                     "complete":False}
                            ]} 

